services:
  postgres:
    container_name: pg_sql_book
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: md
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: borrow_books
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - book-net
    restart: unless-stopped

  mail-dev:
    container_name: mail_dev_book
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - book-net

  keycloak:
    container_name: keycloak-book
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - book-net
    command:
      - "start-dev"

  book-api:
    container_name: book-backend
    image: book/backend:1.0.1
    ports:
      - 8088:8088
    networks:
      - book-net
    depends_on:
      - postgres

  book-ui:
    container_name: book-frontend
    image: book/frontend:1.0.1
    ports:
      - 8080:81
    networks:
      - book-net
    depends_on:
      - book-api

networks:
  book-net:
    driver: bridge

volumes:
  postgres:
    driver: local