spring:
  datasource:
    username: md
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/borrow_books
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: mdarenatoacoin@gmail.com
    password: wbvmwvbsllvsflcp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enabled: true
application:
  cors:
    origins: http://localhost:8088/,http://localhost:4200/,http://localhost:8080/
  file:
    upload: ./././uploads
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  security:
    jwt:
      secret-key: 62475e6540345f6d714a7e513d4047744051534277793d6259326e792a
      expiration: 86400000 # Day
      #      expiration: 60000 # 1 Min
      refresh-token:
        expiration: 604800000 # 7 Days

server:
  port: 8088