spring:
  datasource:
    username: md
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/borrow_books
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: md
    password: password
    auth: true
    properties:
      mail:
        smtp:
          trust: "*"
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  cors:
    origins: http://localhost:8088/,http://localhost:4200/,http://localhost:8080/,http://localhost:9090/
  file:
    upload: ./././uploads
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  security:
    jwt:
      secret-key: 62475e6540345f6d714a7e513d4047744051534277793d6259326e792a
      expiration: 86400000 # Day
#      expiration: 60000 # 1 Min
      refresh-token:
        expiration: 604800000 # 7 Days

server:
  port: 8088