name: Book backend pipeline

on:
  push:
    branches:
      - develop
      - staging
    paths:
      - backend/book-network/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: 17

      - name: Compile project
        run: |
          cd backend/book-network
          ./mvnw clean compile

  unit-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Running unit tests
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_H2_CONSOLE_ENABLED: "true"
          SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect

        run: |
          cd backend/book-network
          ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup PostgreSQL
        env:
          POSTGRE_URL: jdbc:postgresql://localhost:5432/borrow_books
          POSTGRE_USERNAME: md
          POSTGRE_PASSWORD: password
          POSTGRE_DRIVERCLASSNAME: org.postgresql.Driver
          POSTGRE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE USER md WITH PASSWORD 'password';"
          sudo -u postgres psql -c "ALTER USER md CREATEDB;"
          sudo -u postgres psql -c "CREATE DATABASE borrow_books;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE borrow_books TO md;"

      - name: Building backend
        run: |
          cd backend/book-network
          ./mvnw clean package

  build-image:
    runs-on: ubuntu-latest
    name: Build docker image
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Extract Project Version
        id: extract_version
        run: |
          cd backend/book-network
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v5
        with:
          context: backend/book-network
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/book-backend:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_USERNAME }}/book-backend:latest
          build-args: |
            PROFILE=staging
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}